spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/items_data
    username: "{cipher}b7221341b7d0550390f532af7eb6ffed18593bf0d8988242df84a2802c3f4b38"
    password: "{cipher}a3fee8743f7adb793b4c2879fdfc3babefa937dd02598743cad708fe4af3e2aa"
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-events-listener-group
custom:
  page:
    default-size: 10
  strategy:
    popularity:
      item-is-considered-popular-at-orders-count:
        25
    shoes-size:
      min: 30
      max: 46
  category:
    img-path-prefix:
      men: catalog/src/main/resources/images/category/men/
      women: catalog/src/main/resources/images/category/women/
springdoc:
  api-docs:
    path: /docs # these urls will be used to load the api docs of this service by the api gateway
  swagger-ui:
    enabled: false
server:
  port: 8000
  servlet:
    context-path: /catalog
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  